export { default as usersRoutes } from './users.routes.js'
export { default as personsRoutes } from './persons.routes.js'
export { default as productsRoutes } from './products.routes.js'
export { default as postsRoutes } from './posts.routes.js'
export { default as metricsRoutes } from './metrics.routes.js'
export { default as homeRoutes } from './home.routes.js'
export { default as videoRoutes } from './video.routes.js'
